### ISSUE TITLE
JWT verification fails due to padding of signature

### ISSUE THREAD

**Issue by adamlofts** [Jaguar-dart/jaguar_jwt#5]
This example is a correctly signed token according to https://jwt.io/

```dart

void main() {
  String token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwiYWNjb3VudElkIjoiYWNjb3VudDIifQ.FEqp-uESgVJn064zwiLFUlKlOKKN1eUkFmrJtu4HOWg";
  String secret = "localdev";
  verifyJwtHS256Signature(token, secret);
}
```

However it fails with:

```
Unhandled exception:
JWT hash mismatch!
#0      verifyJwtHS256Signature (package:jaguar_jwt/src/jaguar_jwt.dart:192:30)
#1      main (file:///home/adam/dev/fp3/fp3/yacht/bin/api.dart:244:3)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

The reason for this is that the signatures do not compare correctly because of the padding.

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_jwt/commit/cc2f149d5f24d5f9ed4eb068d7c225c86d71163a.
